#Example reference: https://gist.github.com/ju2wheels/3d1a1dfa498977874d03
FROM <from_the_last_output_file_from_Dockerfile-l2_plus_n>

# MAINTAINER FirstName LastName <first.last@company.com>
MAINTAINER TheButler InTheStudy WithTheLeadpipe <jenkins.cicd@landline.com>

