#Example reference: https://gist.github.com/ju2wheels/3d1a1dfa498977874d03
FROM tomcat:7-jre8

# MAINTAINER FirstName LastName <first.last@company.com>
MAINTAINER System Administrator <sys.admin@landline.com>

